export const CARD_TYPE = {
    ALL: "00",
    VISA: "01",
    MASTERCARD: "02",
    AMEX: "03",
    DISCOVER: "04",
    DINERCLUB: "05",
    ENROUTE: "06",
    JCB: "07",
    REVOLUTIONCARD: "08",
    OTHER: "09",
}

export const REPORT_TRAN_TYPE = {
    LOCALTOTALREPORT: "R00",
    LOCALDETAILREPORT: "R02",
    LOCALFAILEDREPORT: "R03",
    HOSTREPORT: "R04",
    HISTORYREPORT: "R05",
    SAFSUMMARYREPORT: "R06",
}

export const EDC_TYPE = {
    ALL: "00",
    CREDIT: "01",
    DEBIT: "02",
    CHECK: "03",
    EBT: "04",
    GIFT: "05",
    LOYALTY: "06",
    CASH: "07",
}

export const OLD_TRANS_TYPE = {
    MENU: '00',
    SALE: '01',
    RETURN: '02',
    AUTH: '03',
    POST_AUTH: '04',
    FORCED: '05',
    ADJUST: '06',
    VOID: '16',
    VOID_SALE: '17',
    VOID_RETURN: '18',
    VOID_AUTH: '19',
    VOID_POST: '20',
    VOID_FRCD: '21',
}

export const TRANS_TYPE = {
    UNKNOWN: '00',
    AUTH: '01',
    SALE: '02',
    RETURN: '03',
    VOID: '04',
    POST_AUTH: '05',
    FORCE_AUTH: '06',
    CAPTURE: '07',
    REPEAT_SALE: '08',
    CAPTURE_ALL: '09',
    ADJUST: '10',
    INQUIRY: '11',
    ACTIVATE: '12',
    DEACTIVATE: '13',
    RELOAD: '14',
    VOID_SALE: '15',
    VOID_RETURN: '16',
    VOID_AUTH: '17',
    VOID_POST_AUTH: '18',
    VOID_FORCE_AUTH: '19',
    VOID_WITHDRAWAL: '20',
    REVERSAL: '21',
    WITHDRAWAL: '22',
    ISSUE: '23',
    CASHOUT: '24',
    REPLACE: '25',
    MERGE: '26',
    REPORT_LOST: '27',
    REDEEM: '28',
    STATUS_CHECK: '29',
    SETUP: '30',
    INIT: '31',
    VERIFY: '32',
    REACTIVATE: '33',
    FORCEDISSUE: '34',
    FORCEDADD: '35',
    UNLOAD: '36',
    RENEW: '37',
    TOKENIZE: '38',
    GETC_ONVERT_DETAIL: '39',
    CONVERT: '40',
}

export const ENTRY_MODE = {
    MANUAL: "00",
    SWIPE: "01",
    CONTACT_LESS: "02",
    SCANNER: "03",
    CHIP: "04",
    CHIP_FALL_BACK_SWIPE: "05",
}